// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pWV8b-0eODxuWfLqcDf2flL2p6wi4-A',
    appId: '1:422287768695:android:bd8251bf46939afa889a72',
    messagingSenderId: '422287768695',
    projectId: 'skippingfrog',
    storageBucket: 'skippingfrog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTQUckmw203I8fy9G9tlyNKxFe-fVfVk',
    appId: '1:422287768695:ios:b6ddcff667a31f74889a72',
    messagingSenderId: '422287768695',
    projectId: 'skippingfrog',
    storageBucket: 'skippingfrog.appspot.com',
    iosClientId: '422287768695-pc0f9v41tg7t00b5n27glj16fm1vhheh.apps.googleusercontent.com',
    iosBundleId: 'com.drcoderz.skippingfrog',
  );

  static const skippingfrog_ios_debug = 'F5230B69-2A30-4BAE-A75C-7406498A7C3B';
  static const skippingfrog_android_debug = 'fa280e69-b89d-4458-b615-9316037a5d49';
  
}
